"""
General utility functions.
"""

from __future__ import annotations

import os
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from functools import cache
from os.path import abspath, dirname, isfile, join, normpath
from random import choice
from typing import TYPE_CHECKING, TypeAlias
from urllib.parse import urlsplit, urlunsplit

from dotenv import dotenv_values, find_dotenv, load_dotenv

from yellowdog_cli.utils.limits import YD_NAME_MAX_LENGTH
from yellowdog_cli.utils.paths import relative_if_possible
from yellowdog_cli.utils.printing import print_debug, print_warning
from yellowdog_cli.utils.settings import NAME_START_PREFIX, YD_ENV_OVERRIDE
from yellowdog_cli.utils.type_check import check_str

if TYPE_CHECKING:
    from yellowdog_client.model import (
        ComputeRequirement,
        ConfiguredWorkerPool,
        ProvisionedWorkerPool,
        WorkRequirement,
    )

UTCNOW = datetime.now(timezone.utc)


def pathname_relative_to_config_file(config_file_dir: str, file: str) -> str:
    """
    Find the pathname of a file relative to the location
    of the config file
    """
    return normpath(relative_if_possible(join(config_file_dir, file)))


# Lower case base 36, for the process discriminator added by generate_id()
# and for random_base36()
BASE36_DIGITS = "0123456789abcdefghijklmnopqrstuvwxyz"

# The PID of the running process, behind the '{{pid}}' variable substitution.
# Captured once at import, like UTCNOW, so that every substitution made during
# a command carries the same value.
PID = os.getpid()

# The process discriminator: 'pid % 1296' in two base 36 digits, behind the
# '{{pid2}}' variable substitution, so that a hand-written name can be
# disambiguated in exactly the way a name generated by generate_id() is.
_PID_MODULO = PID % (36 * 36)
PROCESS_DISCRIMINATOR = (
    BASE36_DIGITS[_PID_MODULO // 36] + BASE36_DIGITS[_PID_MODULO % 36]
)


def random_base36(digits: int) -> str:
    """
    A random string of lower case base 36 digits. Base 36 rather than
    hexadecimal because it is the widest alphabet a YellowDog name may be
    built from, so it packs the most randomness into the fewest characters.
    """
    return "".join(choice(BASE36_DIGITS) for _ in range(digits))


def generate_id(prefix: str = "", max_length: int = 60) -> str:
    """
    Add a UTC timestamp and a process discriminator, and check length.
    """
    # Seconds to one decimal place, then a hyphen and the PID in two base 36
    # digits. The timestamp on its own does not make the name unique: UTCNOW is
    # set when this module is imported, so commands launched together -- from
    # yd-commander, or a shell loop -- reach that import within the same
    # millisecond and generate identical names. Processes that are alive at the
    # same time always have distinct PIDs, and consecutive launches get
    # adjacent ones, so 'pid % 1296' separates them unless 1296 processes were
    # spawned in between. The hyphen marks the last two digits as something
    # other than a continuation of the timestamp.
    generated_id = (
        prefix + UTCNOW.strftime("_%y%m%d-%H%M%S%f")[:-5] + f"-{PROCESS_DISCRIMINATOR}"
    )
    if len(generated_id) > max_length:
        raise ValueError(
            f"Generated ID '{generated_id}' would exceed maximum length ({max_length})"
        )
    return generated_id


# Utility functions for creating links to YD entities
_EntityType: TypeAlias = "ConfiguredWorkerPool | ProvisionedWorkerPool | WorkRequirement | ComputeRequirement"

entities: dict[str, str] = {
    "ConfiguredWorkerPool": "workers",
    "ProvisionedWorkerPool": "workers",
    "WorkRequirement": "work",
    "ComputeRequirement": "compute",
}


def shown_expiry(expiry: datetime | None) -> str:
    """
    A Worker Pool token's expiry time as printed: to the second, with its
    time zone, since the Platform gives it in UTC and the log timestamps
    beside it are local; 'never' for a token the Platform gave none.
    """
    if expiry is None:
        return "never"
    return expiry.isoformat(sep=" ", timespec="seconds")


def link_entity(base_url: str, entity: _EntityType) -> str:
    entity_type_name = type(entity).__name__
    return link(
        base_url,
        f"#/{entities.get(entity_type_name)}/{entity.id}",  # type: ignore[union-attr]
        camel_case_split(entity_type_name).upper(),
    )


def portal_netloc(api_netloc: str) -> str | None:
    """
    The Portal's network location for the API's: each hostname label that is
    exactly 'api' becomes 'portal' ('api.yellowdog.ai' gives
    'portal.yellowdog.ai'; a port is kept). None when there is no such label,
    so that 'capital.example.com' or 'myapihost' is never rewritten.
    """
    labels = api_netloc.split(".")
    portal = ["portal" if label.lower() == "api" else label for label in labels]
    return None if portal == labels else ".".join(portal)


def portal_base_url(api_url: str) -> str:
    """
    The Portal's address for an API URL: the API URL with its network
    location rewritten by portal_netloc() where it names an 'api' host, and
    otherwise exactly as it is, path included ('https://host/api' is left
    as it is), less any trailing '/', query or fragment.
    """
    parts = urlsplit(api_url)
    netloc = portal_netloc(parts.netloc) or parts.netloc
    return urlunsplit((parts.scheme, netloc, parts.path.rstrip("/"), "", ""))


def link(base_url: str, url_suffix: str = "", text: str | None = None) -> str:
    """
    A link to a Portal page: 'url_suffix' under portal_base_url(base_url).
    """
    url = portal_base_url(base_url) + "/" + url_suffix
    if not text:
        text = url
    if text == url:
        return url
    else:
        return f"{text} ({url})"


def camel_case_split(value: str) -> str:
    return " ".join(re.findall(r"[A-Z](?:[a-z]+|[A-Z]*(?=[A-Z]|$))", value))


def add_batch_number_postfix(name: str, batch_number: int, num_batches: int) -> str:
    """
    Generate a name using batch details.
    """
    if num_batches > 1:
        name += "_" + str(batch_number + 1).zfill(len(str(num_batches)))
    return name


#
# Functions for handling delimited variables within strings.
#
@dataclass(order=True)
class Substring:
    start: int
    end: int


def get_delimited_string_boundaries(
    input_string: str,
    opening_delimiter: str,
    closing_delimiter: str,
) -> list[Substring]:
    """
    Given an input string and a pair of opening and closing delimiter strings,
    find the list of start and end indices for the top-level strings enclosed
    by the opening and closing delimiters.

    For example:
        if input_string = "abc {{{{x}}_hello}} 234 {{{{world}}}}",
        and opening_delimiter = "{{", closing_delimiter = "}}",
        the function will return Substring objects: [(4, 19), (24, 37)]

    Opening and closing delimiters must be balanced across the entire
    input_string, otherwise an exception will be raised. Braces inside an
    expression are its content: see _scan_delimited().
    """
    return _scan_delimited(
        input_string, opening_delimiter, closing_delimiter, lenient=False
    )


def find_delimited_expressions(
    s: str, opening_delimiter: str, closing_delimiter: str
) -> list[str]:
    """
    Find the top-level delimited expressions in a string, each one balanced
    and on a single line, in the order they appear.

    Unlike get_delimited_string_boundaries(), this does not require the
    delimiters to balance across the whole string, which is what lets it
    scan the text of a specification file: there a closing delimiter with
    nothing open, such as the '}}' ending a JSON object, is ordinary text,
    and an expression left open at the end of its line is not an expression.

    For example:
      when called with ('{"a":{"b":"{{x_{{y}}}}"}}', "{{", "}}")
      the result is: ['{{x_{{y}}}}']
    """
    return [
        s[span.start : span.end]
        for span in find_delimited_expression_spans(
            s, opening_delimiter, closing_delimiter
        )
    ]


def find_delimited_expression_spans(
    s: str, opening_delimiter: str, closing_delimiter: str
) -> list[Substring]:
    """
    Where find_delimited_expressions() finds its expressions, for a caller
    that substitutes each by its position rather than by its text.
    """
    return _scan_delimited(s, opening_delimiter, closing_delimiter, lenient=True)


# How much of a value an error about its delimiters quotes
_SHOWN_VALUE_LENGTH = 200


@cache
def _inside_expression_pattern(
    opening_delimiter: str, closing_delimiter: str
) -> re.Pattern:
    """
    What _scan_delimited() looks for inside an expression: either delimiter,
    or a single brace. Compiled once per pair, since it is called per value.
    """
    opening_brace, closing_brace = opening_delimiter[-1], closing_delimiter[0]
    tokens = [opening_delimiter, closing_delimiter]
    if opening_brace != closing_brace:
        tokens += [opening_brace, closing_brace]
    return re.compile("|".join(re.escape(token) for token in tokens))


def _scan_delimited(
    s: str, opening_delimiter: str, closing_delimiter: str, lenient: bool
) -> list[Substring]:
    """
    The spans of the top-level delimited expressions in a string, for the two
    functions above, which must agree on where an expression ends: one finds
    the expressions in a file's text, the other splits each one to substitute
    it. Strict, a delimiter that does not balance raises ValueError; lenient,
    it is text, and so is an expression left open at the end of its line.

    Inside an expression, a single brace -- the last character of the opening
    delimiter, or the first of the closing one -- is content, and a closing
    brace that closes one opened in the content is content too. That is what
    lets a default hold braces of its own: '{{table:t:={"a":1}}}' ends at its
    last '}}', not its first, and so does '{{cmd:=echo ${HOME}}}'. Outside an
    expression a brace is plain text, so the JSON around '{"n":{{x}}}' ends
    the expression at its first '}}'.
    """
    # Jump from one delimiter to the next rather than stepping through the
    # text a character at a time, which cost ~18ms on a 500kB specification
    # against ~1.5ms this way. Outside an expression only the next opening
    # delimiter is looked for, with str.find(); single braces are looked for
    # only while one is open, and a line break only then, between one match
    # and the next, rather than matched throughout the text
    # The value quoted at most in part: it can be long (inline Task Data) or
    # hold a substituted credential
    shown = s if len(s) <= _SHOWN_VALUE_LENGTH else s[:_SHOWN_VALUE_LENGTH] + "..."
    mismatched = ValueError(
        f"Mismatched variable delimiters ('{opening_delimiter}', '{closing_delimiter}')"
        f" in '{shown}'"
    )
    inside = _inside_expression_pattern(opening_delimiter, closing_delimiter)
    opening_brace, closing_brace = opening_delimiter[-1], closing_delimiter[0]

    spans: list[Substring] = []
    # For each expression open, innermost last, the braces its content has open
    open_braces: list[int] = []
    start = 0
    position = 0
    while True:
        if not open_braces:  # Only an opening delimiter matters, so find it
            start = s.find(opening_delimiter, position)
            before = start if start != -1 else len(s)
            if not lenient and s.find(closing_delimiter, position, before) != -1:
                raise mismatched  # A closing delimiter with nothing open
            if start == -1:
                break
            open_braces.append(0)
            position = start + len(opening_delimiter)
            continue

        match = inside.search(s, position)
        if match is None:
            break
        if lenient and s.find("\n", position, match.start()) != -1:
            open_braces = []  # The open expression ended with its line
            position = match.start()  # Read this match again, outside one
            continue
        position = match.end()
        token = match.group()
        if token == opening_delimiter:
            open_braces.append(0)
        elif token == closing_delimiter and open_braces[-1] > 0:
            # Its first character closes a brace the content opened
            open_braces[-1] -= 1
            position = match.start() + len(closing_brace)
        elif token == closing_delimiter:
            open_braces.pop()
            if not open_braces:
                spans.append(Substring(start=start, end=match.end()))
        elif token == opening_brace:
            open_braces[-1] += 1
        elif open_braces[-1] > 0:  # A closing brace
            open_braces[-1] -= 1

    if open_braces and not lenient:
        raise mismatched
    return spans


def split_delimited_string(
    s: str, opening_delimiter: str, closing_delimiter: str
) -> list[str]:
    """
    This function takes a string containing delimited sections and breaks it
    into a list of strings, including the non-delimited sections.
    Delimiters are retained.

    For example:
      when called with ("one{{two}}three{{{{four}}}}five", "{{", "}}")
      the result is: ['one', '{{two}}', 'three', '{{{{four}}}}', 'five']
    """

    # Get delimited boundaries
    delimited_boundaries: list[Substring] = get_delimited_string_boundaries(
        s, opening_delimiter, closing_delimiter
    )

    if not delimited_boundaries:
        return [s]

    # Get non-delimited boundaries (i.e., the gaps)
    non_delimited_boundaries: list[Substring] = []
    if delimited_boundaries[0].start > 0:  # Non-variable text at start?
        non_delimited_boundaries.insert(
            0, Substring(start=0, end=delimited_boundaries[0].start)
        )
    for index in range(len(delimited_boundaries) - 1):
        non_delimited_boundaries.insert(
            index + 1,
            (
                Substring(
                    start=delimited_boundaries[index].end,
                    end=delimited_boundaries[index + 1].start,
                )
            ),
        )
    # Non-variable text at end?
    final_boundary: int = delimited_boundaries[len(delimited_boundaries) - 1].end
    if len(s) > final_boundary:
        non_delimited_boundaries.append(Substring(start=final_boundary, end=len(s)))

    return [
        s[boundary.start : boundary.end]
        for boundary in sorted(non_delimited_boundaries + delimited_boundaries)  # type: ignore[type-var]
    ]


# The kinds of name change already warned of in this run (see
# _warn_of_name_change_once())
_NAME_CHANGES_WARNED: set[str] = set()


def _warn_of_name_change_once(kind: str, message: str) -> None:
    """
    Warn of a kind of name change the first time it is made in the run: Task
    names are formatted one per Task, and a warning for each would bury the
    rest of the output.
    """
    if kind in _NAME_CHANGES_WARNED:
        return
    _NAME_CHANGES_WARNED.add(kind)
    print_warning(f"{message} (later names changed so are not reported)")


def format_yd_name(yd_name: str, add_prefix: bool = True) -> str:
    """
    Format a string to be consistent with YellowDog naming requirements:
    prefixed with NAME_START_PREFIX, with a warning, where it would not
    start with a letter; and, with a warning once per run, stripped of
    characters a name cannot hold and cut to YD_NAME_MAX_LENGTH. The
    documented substitutions (lower case, ' ' and '.' to '_', '/' to '-')
    are made without one. A caller formatting a name *component* rather than
    a whole name -- the 'format_name:' type tag -- passes add_prefix=False
    and gets neither the prefix nor the warnings.
    """
    # A name that isn't a String -- 'name = 123' in a configuration or
    # specification file -- is a configuration error, and is reported as one
    # rather than failing in the substitutions below
    check_str(yd_name)

    # Make obvious substitutions
    substituted = yd_name.replace("/", "-").replace(" ", "_").replace(".", "_").lower()

    # Enforce acceptable regex
    new_yd_name = re.sub("[^a-z0-9_-]", "", substituted)
    characters_dropped = new_yd_name != substituted

    if new_yd_name == "":
        raise ValueError(
            f"'{yd_name}' contains no characters usable in a YellowDog name"
        )

    # Must start with an alphabetic character
    prefix_added = add_prefix and not new_yd_name[0].isalpha()
    if prefix_added:
        new_yd_name = NAME_START_PREFIX + new_yd_name

    cut_short = len(new_yd_name) > YD_NAME_MAX_LENGTH
    new_yd_name = new_yd_name[:YD_NAME_MAX_LENGTH]

    # Warned about after truncation, so that the reported name is the one that
    # will actually be used
    if add_prefix and characters_dropped:
        _warn_of_name_change_once(
            "characters dropped",
            f"Name '{yd_name}' has characters a YellowDog name cannot hold:"
            f" using '{new_yd_name}' instead",
        )
    if add_prefix and cut_short:
        _warn_of_name_change_once(
            "cut short",
            f"Name '{yd_name}' is longer than {YD_NAME_MAX_LENGTH} characters:"
            f" using '{new_yd_name}' instead",
        )
    if prefix_added:
        print_warning(
            f"Name '{yd_name}' doesn't start with a letter: "
            f"using '{new_yd_name}' instead"
        )

    return new_yd_name


def dotenv_file_path(config_file: str | None) -> str | None:
    """
    The .env file a command would load: one beside the config file
    ('config_file', else config.toml) first, else the nearest one found
    upwards from the current directory; None when there is neither.
    """
    # Check the config file's directory first (covers the case where the user
    # runs from a different directory than where config.toml lives), then
    # fall back to searching upward from CWD.
    config_path = config_file or "config.toml"
    config_dir_dotenv = join(dirname(abspath(config_path)), ".env")
    if isfile(config_dir_dotenv):
        return config_dir_dotenv
    return find_dotenv(usecwd=True) or None


def load_dotenv_file(config_file: str | None, env_override: bool = False):
    """
    Load extra environment variables from a .env file if it exists.
    Do not override existing variables (environment takes precedence)
    unless --env-override is set or YD_ENV_OVERRIDE is set in the environment.
    Report on YD vars that are taken from .env.
    """
    dotenv_file = dotenv_file_path(config_file)
    if dotenv_file is None:
        return

    env_override = env_override or bool(os.environ.get(YD_ENV_OVERRIDE))

    print_debug(
        f"Loading environment variables from '{dotenv_file}' ("
        f"{'OVERRIDING' if env_override else 'NOT OVERRIDING'} existing variables)"
    )

    dotenv_yd_substitutions = [  # Find 'YD' variables
        f"'{key}'"
        for key in dotenv_values(dotenv_file)
        if key.startswith("YD") and (os.environ.get(key) is None or env_override)
    ]

    if dotenv_yd_substitutions:
        print_debug(
            f"Adding 'YD' environment variable(s): {', '.join(dotenv_yd_substitutions)}"
        )

    # Actually load the variables (including non-'YD' variables)
    load_dotenv(dotenv_file, override=env_override)


def is_http_not_found(e: Exception) -> bool:
    """
    Return True if the exception is an HTTP 404 (not found) error from the
    platform API. Use this instead of matching on exception message text.
    """
    if "requests" not in sys.modules:
        return False  # an HTTPError can only come from a loaded 'requests'
    from requests.exceptions import HTTPError

    return (
        isinstance(e, HTTPError)
        and e.response is not None
        and e.response.status_code == 404
    )


def config_file_explicitly_selected(args) -> bool:
    """
    True if the configuration file was explicitly selected using the
    '--config'/'-c' option, on the command line 'args'. An explicitly
    selected config file takes precedence over environment variables (but
    not over the command line).
    """
    return args.config_file is not None
