"""
General utility functions.
"""

import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from os.path import abspath, dirname, isfile, join, normpath, relpath
from typing import TypeAlias
from urllib.parse import urlparse

from dotenv import dotenv_values, find_dotenv, load_dotenv
from requests.exceptions import HTTPError
from yellowdog_client.model import (
    ComputeRequirement,
    ConfiguredWorkerPool,
    ProvisionedWorkerPool,
    WorkRequirement,
)

from yellowdog_cli.utils.args import ARGS_PARSER
from yellowdog_cli.utils.printing import print_info, print_warning
from yellowdog_cli.utils.settings import NAME_START_PREFIX, YD_ENV_OVERRIDE

UTCNOW = datetime.now(timezone.utc)


def pathname_relative_to_config_file(config_file_dir: str, file: str) -> str:
    """
    Find the pathname of a file relative to the location
    of the config file
    """
    return normpath(relpath(join(config_file_dir, file)))


# Lower case base 36, for the process discriminator added by generate_id()
BASE36_DIGITS = "0123456789abcdefghijklmnopqrstuvwxyz"

# The process discriminator: 'pid % 1296' in two base 36 digits. Computed once
# at import, like UTCNOW, so that the '{{pid}}' variable substitution and any
# name generated by generate_id() always carry the same value in one command.
_PID = os.getpid() % (36 * 36)
PROCESS_DISCRIMINATOR = BASE36_DIGITS[_PID // 36] + BASE36_DIGITS[_PID % 36]


def generate_id(prefix: str = "", max_length: int = 60) -> str:
    """
    Add a UTC timestamp and a process discriminator, and check length.
    """
    # Seconds to one decimal place, then a hyphen and the PID in two base 36
    # digits. The timestamp on its own does not make the name unique: UTCNOW is
    # set when this module is imported, so commands launched together -- from
    # yd-commander, or a shell loop -- reach that import within the same
    # millisecond and generate identical names. Processes that are alive at the
    # same time always have distinct PIDs, and consecutive launches get
    # adjacent ones, so 'pid % 1296' separates them unless 1296 processes were
    # spawned in between. The hyphen marks the last two digits as something
    # other than a continuation of the timestamp.
    generated_id = (
        prefix + UTCNOW.strftime("_%y%m%d-%H%M%S%f")[:-5] + f"-{PROCESS_DISCRIMINATOR}"
    )
    if len(generated_id) > max_length:
        raise ValueError(
            f"Error: Generated ID '{generated_id}' would exceed "
            f"maximum length ({max_length})"
        )
    return generated_id


# Utility functions for creating links to YD entities
_EntityType: TypeAlias = (
    ConfiguredWorkerPool | ProvisionedWorkerPool | WorkRequirement | ComputeRequirement
)

entities: dict[str, str] = {
    "ConfiguredWorkerPool": "workers",
    "ProvisionedWorkerPool": "workers",
    "WorkRequirement": "work",
    "ComputeRequirement": "compute",
}


def link_entity(base_url: str, entity: _EntityType) -> str:
    entity_type_name = type(entity).__name__
    return link(
        base_url,
        f"#/{entities.get(entity_type_name)}/{entity.id}",  # type: ignore[union-attr]
        camel_case_split(entity_type_name).upper(),
    )


def link(base_url: str, url_suffix: str = "", text: str | None = None) -> str:
    url_parts = urlparse(base_url)
    netloc = url_parts.netloc.replace("api", "portal")
    base_url = url_parts.scheme + "://" + netloc
    url = base_url + "/" + url_suffix
    if not text:
        text = url
    if text == url:
        return url
    else:
        return f"{text} ({url})"


def camel_case_split(value: str) -> str:
    return " ".join(re.findall(r"[A-Z](?:[a-z]+|[A-Z]*(?=[A-Z]|$))", value))


def add_batch_number_postfix(name: str, batch_number: int, num_batches: int) -> str:
    """
    Generate a name using batch details.
    """
    if num_batches > 1:
        name += "_" + str(batch_number + 1).zfill(len(str(num_batches)))
    return name


#
# Functions for handling delimited variables within strings.
#
@dataclass(order=True)
class Substring:
    start: int
    end: int


def get_delimited_string_boundaries(
    input_string: str,
    opening_delimiter: str,
    closing_delimiter: str,
) -> list[Substring]:
    """
    Given an input string and a pair of opening and closing delimiter strings,
    find the list of start and end indices for the top-level strings enclosed
    by the opening and closing delimiters.

    For example:
        if input_string = "abc {{{{x}}_hello}} 234 {{{{world}}}}",
        and opening_delimiter = "{{", closing_delimiter = "}}",
        the function will return Substring objects: [(4, 19), (24, 37)]

    Opening and closing delimiters must be balanced across the entire
    input_string, otherwise an exception will be raised.
    """
    # Escape the delimiters: they are literal strings, not regex patterns
    openings = [
        (x.span()[0], 1)
        for x in re.finditer(re.escape(opening_delimiter), input_string)
    ]
    closings = [
        (x.span()[0], -1)
        for x in re.finditer(re.escape(closing_delimiter), input_string)
    ]

    mismatched_delimiters_exception = ValueError(
        f"Mismatched variable delimiters ('{opening_delimiter}', '{closing_delimiter}')"
        f" in '{input_string}'"
    )

    if len(openings) != len(closings):
        raise mismatched_delimiters_exception

    slate = 0
    start = None
    substrings: list[Substring] = []

    for boundary in sorted(openings + closings):
        slate += boundary[1]
        if slate < 0:
            raise mismatched_delimiters_exception
        if slate == 1 and start is None:
            start = boundary[0]
        elif slate == 0:
            assert start is not None  # set when slate first reached 1
            substrings.append(
                Substring(start=start, end=boundary[0] + len(closing_delimiter))
            )
            start = None

    if slate > 0:
        raise mismatched_delimiters_exception

    return substrings


def split_delimited_string(
    s: str, opening_delimiter: str, closing_delimiter: str
) -> list[str]:
    """
    This function takes a string containing delimited sections and breaks it
    into a list of strings, including the non-delimited sections.
    Delimiters are retained.

    For example:
      when called with ("one{{two}}three{{{{four}}}}five", "{{", "}}")
      the result is: ['one', '{{two}}', 'three', '{{{{four}}}}', 'five']
    """

    # Get delimited boundaries
    delimited_boundaries: list[Substring] = get_delimited_string_boundaries(
        s, opening_delimiter, closing_delimiter
    )

    if not delimited_boundaries:
        return [s]

    # Get non-delimited boundaries (i.e., the gaps)
    non_delimited_boundaries: list[Substring] = []
    if delimited_boundaries[0].start > 0:  # Non-variable text at start?
        non_delimited_boundaries.insert(
            0, Substring(start=0, end=delimited_boundaries[0].start)
        )
    for index in range(len(delimited_boundaries) - 1):
        non_delimited_boundaries.insert(
            index + 1,
            (
                Substring(
                    start=delimited_boundaries[index].end,
                    end=delimited_boundaries[index + 1].start,
                )
            ),
        )
    # Non-variable text at end?
    final_boundary: int = delimited_boundaries[len(delimited_boundaries) - 1].end
    if len(s) > final_boundary:
        non_delimited_boundaries.append(Substring(start=final_boundary, end=len(s)))

    return [
        s[boundary.start : boundary.end]
        for boundary in sorted(non_delimited_boundaries + delimited_boundaries)  # type: ignore[type-var]
    ]


def remove_outer_delimiters(
    input_string: str, opening_delimiter: str, closing_delimiter: str
) -> str:
    """
    Remove the outermost delimiters from a string.
    There is no checking for a well-formed string.
    """
    # The string and the closing delimiter must be reversed ([::-1]) for
    # removal, then re-reversed
    return input_string.replace(f"{opening_delimiter}", "", 1)[::-1].replace(
        f"{closing_delimiter[::-1]}", "", 1
    )[::-1]


def format_yd_name(yd_name: str, add_prefix: bool = True) -> str:
    """
    Format a string to be consistent with YellowDog naming requirements.
    """
    # Make obvious substitutions
    new_yd_name = yd_name.replace("/", "-").replace(" ", "_").replace(".", "_").lower()

    # Enforce acceptable regex
    new_yd_name = re.sub("[^a-z0-9_-]", "", new_yd_name)

    if new_yd_name == "":
        raise ValueError(
            f"'{yd_name}' contains no characters usable in a YellowDog name"
        )

    # Must start with an alphabetic character
    prefix_added = add_prefix and not new_yd_name[0].isalpha()
    if prefix_added:
        new_yd_name = NAME_START_PREFIX + new_yd_name

    # Mustn't exceed 60 chars
    new_yd_name = new_yd_name[:60]

    # Warned about after truncation, so that the reported name is the one that
    # will actually be used
    if prefix_added:
        print_warning(
            f"Name '{yd_name}' doesn't start with a letter: "
            f"using '{new_yd_name}' instead"
        )

    return new_yd_name


def load_dotenv_file():
    """
    Load extra environment variables from a .env file if it exists.
    Do not override existing variables (environment takes precedence)
    unless --env-override is set or YD_ENV_OVERRIDE is set in the environment.
    Report on YD vars that are taken from .env.
    """
    # Check the config file's directory first (covers the case where the user
    # runs from a different directory than where config.toml lives), then
    # fall back to searching upward from CWD.
    config_path = ARGS_PARSER.config_file or "config.toml"
    config_dir_dotenv = join(dirname(abspath(config_path)), ".env")
    if isfile(config_dir_dotenv):
        dotenv_file = config_dir_dotenv
    else:
        dotenv_file = find_dotenv(usecwd=True)

    if not dotenv_file:
        return

    env_override = bool(ARGS_PARSER.env_override) or bool(
        os.environ.get(YD_ENV_OVERRIDE)
    )

    print_info(
        f"Loading environment variables from '{dotenv_file}' ("
        f"{'OVERRIDING' if env_override else 'NOT OVERRIDING'} existing variables)"
    )

    dotenv_yd_substitutions = [  # Find 'YD' variables
        f"'{key}'"
        for key in dotenv_values(dotenv_file)
        if key.startswith("YD") and (os.environ.get(key) is None or env_override)
    ]

    if dotenv_yd_substitutions:
        print_info(
            f"Adding 'YD' environment variable(s): {', '.join(dotenv_yd_substitutions)}"
        )

    # Actually load the variables (including non-'YD' variables)
    load_dotenv(dotenv_file, override=env_override)


def is_http_not_found(e: Exception) -> bool:
    """
    Return True if the exception is an HTTP 404 (not found) error from the
    platform API. Use this instead of matching on exception message text.
    """
    return (
        isinstance(e, HTTPError)
        and e.response is not None
        and e.response.status_code == 404
    )


def config_file_explicitly_selected(args_parser) -> bool:
    """
    True if the configuration file was explicitly selected using the
    '--config'/'-c' option. An explicitly selected config file takes
    precedence over environment variables (but not over the command line).

    The caller's ARGS_PARSER is passed in (rather than using this module's
    import) so that tests can patch it per-module.
    """
    return args_parser.config_file is not None
